---
title: "Main"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }

library("RSQLite")
db<-dbConnect(SQLite(),dbname="test.sqlite")
summary(db)

# Create Senator table 
dbRemoveTable(db, "Senators_PI")
dbSendQuery(conn=db, "CREATE TABLE Senators_PI (Username TEXT PRIMARY KEY, Name TEXT, State TEXT)")
#dbWriteTable(conn = db, name = "senatorsdf", value = senators, row.names = F, append = T)
dbReadTable(db, "Senators_PI")

# Create Tweet table 
dbRemoveTable(db, "Tweets")
dbSendQuery(conn=db, "CREATE TABLE Tweets (Username TEXT, 
            Status_Idea TEXT, 
            Text TEXT,
            Created_at TEXT,
            Is_Retweet INTEGER,
            Favorite_count INT, 
            Hashtag TEXT, 
            PRIMARY KEY (Username, Status_Idea))")
#dbWriteTable(conn = db, name = "tweetsdf", value = senators, row.names = F, append = T)
dbReadTable(db, "Tweets")

# Additional data
dbRemoveTable(db, "Tweet_Metadata")
dbSendQuery(conn=db, "CREATE TABLE Tweet_Metadata (Username TEXT, 
            Status_Idea TEXT PRIMARY KEY, 
            Source TEXT,
            Reply_to_screen_name TEXT,
            Lang TEXT,
            Quoted_text TEXT,
            Quoted_source TEXT,
            Status_url TEXT,
            Description TEXT, 
            Followers_count INTEGER,
            Friends_count INTEGER,
            Statuses_count INTEGER, 
            Verified INT,
            Profile_url TEXT)")
#dbWriteTable(conn = db, name = "tweetsmetadatadf", value = senators, row.names = F, append = T)
dbReadTable(db, "Tweet_Metadata")

dbListTables(db)

```

