---
title: "SenatorDataCatu"
output: html_document
---
```{r}
library(rtweet)
library(httr)
library(tidyverse)
library(rvest)
library(xml2)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

access_token_secret <- "tGRqQT1Owz7DCVLZtEl2bSoR0gId4ptP5px7tjE5Otu0w" #replace with your access token secret
consumer_key       <- "GnrmA9Nba0B7xC7GarjW0hO9I" #replace with your key
consumer_secret    <- "A9MTNshOxb8K2ftaxEyt8GiknPGynFwoiG8AHCw2OxiUtXD4UD" #replace with your secret
access_token       <- "1040648642-wL4eOa9zEP5VpYvKrZMSMOERqdhGQu9XCYIA4Ym" #replace with your access token
appname <- "DS4100 Catu App"


# create token named "twitter_token"
twitter_token <- rtweet::create_token(app = appname,
                                      consumer_key = consumer_key,
                                      consumer_secret = consumer_secret,
                                      access_token = access_token,
                                      access_secret = access_token_secret)
```


```{r}
load("senatorDataDF.Rda")
View(senatorsdf)
end_senators_1 <- senatorsdf[c(67:75),]
end_senators_2 <- senatorsdf[c(76:83),]
end_senators_3 <- senatorsdf[c(84:91),]
end_senators_4 <- senatorsdf[c(92:100),]
#View(senatorData)
```

```{r get tweets}
tweets_end_1 <- get_timeline(end_senators_1$twitter, n = 80, max_id = NULL, home = FALSE, parse = TRUE, check = TRUE, token = NULL)
rate_limit()
tweets_end_2 <- get_timeline(end_senators_2$twitter, n = 80, max_id = NULL, home = FALSE, parse = TRUE, check = TRUE, token = NULL)
tweets_end_3 <- get_timeline(end_senators_3$twitter, n = 80, max_id = NULL, home = FALSE, parse = TRUE, check = TRUE, token = NULL)
tweets_end_4 <- get_timeline(end_senators_4$twitter, n = 80, max_id = NULL, home = FALSE, parse = TRUE, check = TRUE, token = NULL)

tweets_end_all <- rbind(tweets_end_1, tweets_end_2)
tweets_end_all <- rbind(tweets_end_all, tweets_end_3)
tweets_end_all <- rbind(tweets_end_all, tweets_end_4)

save(tweets_end_all, file="tweetsEndAll.Rda")
```
