---
title: "SenatorDataFiona"
output: html_document
---
```{r}
library(rtweet)
library(httr)
library(tidyverse)
library(rvest)
library(xml2)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

access_token_secret <- "Of6QTP7pwkTsTYHFwQlYLQg823W2AKpN6DZgYhKtXjGdi" #replace with your access token secret
consumer_key       <- "5SaCvXY1dpgCU6Y6asgNDom8K" #replace with your key
consumer_secret    <- "oq6AQaLxX0MOd59CBybjfeFZkIf7zwIcMqRTsLv14MjYLZVvfh" #replace with your secret
access_token       <- "1083775188557332480-zWK74tIZDYEZFSg3IlamrcNT5gZ95F" #replace with your access token
appname <- "ds4100_project"


# create token named "twitter_token"
twitter_token <- rtweet::create_token(app = appname,
                                      consumer_key = consumer_key,
                                      consumer_secret = consumer_secret,
                                      access_token = access_token,
                                      access_secret = access_token_secret)
```


```{r}
load("senatorDataDF.Rda")
View(senatorsdf)
mid_senators_1 <- senatorsdf[c(34:42),]
mid_senators_2 <- senatorsdf[c(43:51),]
mid_senators_3 <- senatorsdf[c(52:60),]
mid_senators_4 <- senatorsdf[c(61:66),]
#View(senatorData)
```

```{r get tweets}
tweets_mid_1 <- get_timeline(mid_senators_1$twitter, n = 80, max_id = NULL, home = FALSE, parse = TRUE, check = TRUE, token = NULL)
rate_limit()
tweets_mid_2 <- get_timeline(mid_senators_2$twitter, n = 80, max_id = NULL, home = FALSE, parse = TRUE, check = TRUE, token = NULL)
tweets_mid_3 <- get_timeline(mid_senators_3$twitter, n = 80, max_id = NULL, home = FALSE, parse = TRUE, check = TRUE, token = NULL)
tweets_mid_4 <- get_timeline(mid_senators_4$twitter, n = 80, max_id = NULL, home = FALSE, parse = TRUE, check = TRUE, token = NULL)

tweets_mid_all <- rbind(tweets_mid_1, tweets_mid_2)
tweets_mid_all <- rbind(tweets_mid_all, tweets_mid_3)
tweets_mid_all <- rbind(tweets_mid_all, tweets_mid_4)

save(tweets_mid_all, file="tweetsMidAll.Rda")
```
